name: API Testing with Keploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Install Keploy
      run: |
        curl -s https://raw.githubusercontent.com/keploy/keploy/main/install.sh | bash
        echo "$HOME/.keploy/bin" >> $GITHUB_PATH
        
    - name: Verify Keploy installation
      run: keploy --version
      
    - name: Run Keploy API tests
      run: |
        # Create reports directory
        mkdir -p keploy-reports
        
        # Run tests
        keploy test --config keploy.yaml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: keploy-test-results
        path: |
          keploy-reports/
          .keploy/
        retention-days: 30
        
    - name: Generate test report
      run: |
        echo "<html><body><h1>Keploy API Test Results</h1>" > keploy-report.html
        echo "<p>Test run completed at $(date)</p>" >> keploy-report.html
        echo "<p>✅ API tests completed successfully</p>" >> keploy-report.html
        echo "<p>📊 Check the uploaded artifacts for detailed results.</p>" >> keploy-report.html
        echo "</body></html>" >> keploy-report.html
        
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: keploy-report
        path: keploy-report.html

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 30 